package com.wangfengbabe.learn.springboot.mybatis.mapper;

import com.wangfengbabe.learn.springboot.mybatis.domain.Account;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

//@Mapper
public interface AccountMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Wed Dec 26 13:31:18 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Wed Dec 26 13:31:18 CST 2018
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Wed Dec 26 13:31:18 CST 2018
     */
    Account selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Wed Dec 26 13:31:18 CST 2018
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Wed Dec 26 13:31:18 CST 2018
     */
    int updateByPrimaryKey(Account record);
}